<?php

namespace LP\PlatformBundle\Repository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{

    public function findCarAdverts($limit = null)
    {
        $qb = $this->createQueryBuilder('a')
            ->innerJoin('a.car', 'c');

        if (false === is_null($limit))
            $qb->setMaxResults($limit);

        return $qb->getQuery()->getResult();
    }

    public function findPromos()
    {
        $qb = $this->createQueryBuilder('a')
            ->where('a.car is NULL');

        return $qb->getQuery()->getResult();
    }

    public function findLastPromo()
    {
        $qb = $this->createQueryBuilder('a')
            ->where('a.car is NULL')
            ->orderBy('a.datePosted', 'DESC')
            ->setMaxResults(1)
            ;

        return $qb->getQuery()->getSingleResult();
    }

}
